/* Purview Gurukul — source of truth links per topic.
   Official US government and standards-body pages the content was checked
   against. Rendered as a "Sources" section at the end of every topic. */
"use strict";
const SOURCES_REVIEWED="7 October 2026";
const S={
  cmsCosts:["Medicare.gov — Medicare costs (2026)","https://www.medicare.gov/basics/costs/medicare-costs"],
  cmsCostsMM:["CMS MM14279 — Deductible, coinsurance and premium rates CY 2026","https://www.cms.gov/files/document/mm14279-medicare-deductible-coinsurance-premium-rates-cy-2026-update.pdf"],
  partsOfMedicare:["Medicare.gov — Parts of Medicare","https://www.medicare.gov/basics/get-started-with-medicare/medicare-basics/parts-of-medicare"],
  partD:["Medicare.gov — Drug coverage costs (Part D cap)","https://www.medicare.gov/health-drug-plans/part-d/basics/costs"],
  mbi:["CMS — Understanding the MBI format","https://www.cms.gov/medicare/new-medicare-card/understanding-the-mbi.pdf"],
  mbiOverview:["CMS — Medicare Beneficiary Identifiers","https://www.cms.gov/training-education/partner-outreach-resources/new-medicare-card/medical-beneficiary-identifiers-mbis"],
  medigap:["Medicare.gov — Medigap basics","https://www.medicare.gov/health-drug-plans/medigap/basics"],
  medigapSwitch:["Medicare.gov — Switching Medigap policies (30-day free look)","https://www.medicare.gov/health-drug-plans/medigap/ready-to-buy/change-policies/switch-drop"],
  msp:["CMS — Medicare Secondary Payer","https://www.cms.gov/medicare/coordination-benefits-recovery/overview/secondary-payer"],
  mspSize:["CMS — MSP employer size guidelines","https://www.cms.gov/Medicare/Coordination-of-Benefits-and-Recovery/Mandatory-Insurer-Reporting-For-Group-Health-Plans/GHP-Training-Material/Downloads/MSP-Employer-Size-for-GHP-Arrangements-Part-1.pdf"],
  whoPaysFirst:["Medicare.gov — Who pays first?","https://www.medicare.gov/health-drug-plans/coordination/who-pays-first"],
  mspManual2:["CMS — MSP Manual chapter 2, MSP provisions","https://www.cms.gov/regulations-and-guidance/guidance/manuals/downloads/msp105c02.pdf"],
  mspEsrd:["CMS — MSP and end-stage renal disease","https://www.cms.gov/medicare/coordination-of-benefits-and-recovery/coordination-of-benefits-and-recovery-overview/medicare-secondary-payer/downloads/msp-end-stage-renal-disease-esrd.pdf"],
  mspDisability:["CMS — MSP and disability","https://www.cms.gov/medicare/coordination-of-benefits-and-recovery/coordination-of-benefits-and-recovery-overview/medicare-secondary-payer/downloads/medicare-secondary-payer-disability.pdf"],
  opmPaysFirst:["OPM — Understand which insurance pays first (FEHB and Medicare)","https://www.opm.gov/healthcare-insurance/medicare/understand-which-insurance-pays-first/"],
  naicCob:["NAIC — Coordination of Benefits Model Regulation (MO-120)","https://content.naic.org/sites/default/files/model-law-120.pdf"],
  tricareOhi:["TRICARE — Using other health insurance","https://tricare.mil/Plans/OHI"],
  champvaCare:["VA — CHAMPVA care (other insurance order)","https://www.va.gov/resources/champva-care/"],
  howMedicareWorks:["Medicare.gov — How Medicare works with other insurance","https://www.medicare.gov/publications/02179-how-medicare-works-with-other-insurance.pdf"],
  cobOverview:["CMS — Coordination of Benefits overview","https://www.cms.gov/medicare/coordination-benefits-recovery/overview"],
  abn:["CMS — Advance Beneficiary Notice (FFS ABN)","https://www.cms.gov/medicare/forms-notices/beneficiary-notices-initiative/ffs-abn"],
  appeals:["Medicare.gov — Appeals in Original Medicare","https://www.medicare.gov/providers-services/claims-appeals-complaints/appeals/original-medicare"],
  redetermination:["CMS — First level of appeal: redetermination","https://www.cms.gov/medicare/appeals-grievances/fee-for-service/first-level-appeal-redetermination-medicare-contractor"],
  overpay:["CMS — Reporting and returning self-identified overpayments (60-day rule)","https://www.cms.gov/newsroom/fact-sheets/medicare-reporting-and-returning-self-identified-overpayments"],
  medicaidElig:["Medicaid.gov — Eligibility policy (incl. medically needy spend-down)","https://www.medicaid.gov/medicaid/eligibility-policy"],
  medicaidTPL:["Medicaid.gov — COB/TPL handbook (payer of last resort)","https://www.medicaid.gov/medicaid/eligibility/downloads/cob-tpl-handbook.pdf"],
  chip:["Medicaid.gov — CHIP eligibility and enrollment","https://www.medicaid.gov/chip/chip-eligibility-enrollment"],
  pace:["Medicare.gov — PACE","https://www.medicare.gov/health-drug-plans/health-plans/your-coverage-options/other-medicare-health-plans/PACE"],
  paceMedicaid:["Medicaid.gov — Program of All-Inclusive Care for the Elderly","https://www.medicaid.gov/medicaid/long-term-services-supports/program-of-all-inclusive-care-for-elderly"],
  tricare:["TRICARE — Regions (East: Humana Military, West: TriWest)","https://tricare.mil/About/Regions"],
  tricareElig:["TRICARE — Eligibility","https://www.tricare.mil/Plans/Eligibility"],
  champva:["VA — CHAMPVA benefits","https://www.va.gov/family-and-caregiver-benefits/health-and-disability/champva/"],
  fehb:["OPM — FEHB Program fast facts","https://www.opm.gov/healthcare-insurance/fastfacts/fehb/"],
  ihs:["IHS — Purchased/Referred Care","https://www.ihs.gov/forpatients/prc/"],
  hipaaPrivacy:["HHS — Summary of the HIPAA Privacy Rule","https://www.hhs.gov/hipaa/for-professionals/privacy/laws-regulations/index.html"],
  hipaaTPO:["HHS — Uses and disclosures for treatment, payment and operations","https://www.hhs.gov/hipaa/for-professionals/privacy/guidance/disclosures-treatment-payment-health-care-operations/index.html"],
  hipaaMin:["HHS — Minimum necessary standard","https://www.hhs.gov/sites/default/files/ocr/privacy/hipaa/understanding/coveredentities/minimumnecessary.pdf"],
  hipaaSecurity:["HHS — HIPAA Security Rule","https://www.hhs.gov/hipaa/for-professionals/security/index.html"],
  hipaaBreach:["HHS — Breach Notification Rule","https://www.hhs.gov/hipaa/for-professionals/breach-notification/index.html"],
  deid:["HHS — De-identification and the 18 identifiers","https://www.hhs.gov/hipaa/for-professionals/special-topics/de-identification/index.html"],
  nsa:["CMS — No Surprises Act: your rights against surprise bills","https://www.cms.gov/newsroom/fact-sheets/no-surprises-understand-your-rights-against-surprise-medical-bills"],
  nsaProvider:["CMS — No Surprises provider requirements","https://www.cms.gov/initiatives/no-surprise-billing/overview/policies-resources/provider-requirements-resources"],
  oop2026:["Federal Register — HHS Notice of Benefit and Payment Parameters for 2026","https://www.federalregister.gov/documents/2025/01/15/2025-00640/patient-protection-and-affordable-care-act-hhs-notice-of-benefit-and-payment-parameters-for-2026-and"],
  hcGlossary:["HealthCare.gov — Glossary of health coverage terms","https://www.healthcare.gov/glossary/"],
  hcOOP:["HealthCare.gov — Out-of-pocket maximum","https://www.healthcare.gov/glossary/out-of-pocket-maximum-limit/"],
  hcGrace:["HealthCare.gov — Grace period","https://www.healthcare.gov/glossary/grace-period/"],
  hcPreventive:["HealthCare.gov — Preventive care benefits","https://www.healthcare.gov/coverage/preventive-care-benefits/"],
  cobra:["DOL — COBRA continuation coverage","https://www.dol.gov/agencies/ebsa/laws-and-regulations/laws/cobra"],
  cobraFaq:["DOL — COBRA FAQs for workers","https://www.dol.gov/agencies/ebsa/about-ebsa/our-activities/resource-center/faqs/cobra-continuation-health-coverage-workers"],
  pos:["CMS — Place of service code set","https://www.cms.gov/medicare/coding-billing/place-of-service-codes/code-sets"],
  posDb:["CMS — POS codes for professional claims","https://www.cms.gov/Medicare/Medicare-Fee-for-Service-Payment/PhysicianFeeSched/Downloads/Website-POS-database.pdf"],
  icd:["CMS — ICD-10-CM official guidelines FY 2026","https://www.cms.gov/files/document/fy-2026-icd-10-cm-coding-guidelines.pdf"],
  icdCdc:["CDC/NCHS — ICD-10-CM","https://www.cdc.gov/nchs/icd/icd-10-cm/index.html"],
  hcpcs:["CMS — Healthcare Common Procedure Coding System (HCPCS)","https://www.cms.gov/medicare/coding-billing/healthcare-common-procedure-system"],
  cpt:["AMA — CPT (code set owner)","https://www.ama-assn.org/practice-management/cpt"],
  ncci:["CMS — National Correct Coding Initiative edits","https://www.cms.gov/medicare/coding-billing/national-correct-coding-initiative-ncci-edits"],
  em:["CMS MLN006764 — Evaluation and management services guide","https://www.cms.gov/files/document/mln006764-evaluation-management-services.pdf"],
  npi:["CMS — National Provider Identifier standard","https://www.cms.gov/regulations-and-guidance/administrative-simplification/nationalprovidentstand"],
  npiBooklet:["CMS — NPI: what you need to know","https://www.cms.gov/files/document/icn902603npibooklet.pdf"],
  pecos:["CMS — Medicare provider enrollment","https://www.cms.gov/medicare/enrollment-renewal/providers-suppliers"],
  pfs:["CMS — Physician Fee Schedule","https://www.cms.gov/medicare/payment/fee-schedules/physician"],
  cms1500:["CMS — CMS-1500 claim form","https://www.cms.gov/medicare/cms-forms/cms-forms/cms-forms-items/cms1188854"],
  nucc:["NUCC — 1500 claim form instruction manual","https://www.nucc.org/"],
  nubc:["NUBC — UB-04 (CMS-1450) data specifications","https://www.nubc.org/"],
  edi:["CMS — Adopted HIPAA transaction standards (X12 5010)","https://www.cms.gov/priorities/key-initiatives/burden-reduction/administrative-simplification/transactions/adopted-standards-and-operating-rules"],
  ediBilling:["CMS — Medicare electronic billing and EDI","https://www.cms.gov/medicare/coding-billing/electronic-billing"],
  codeSets:["CMS — Adopted code sets under HIPAA","https://www.cms.gov/priorities/key-initiatives/burden-reduction/administrative-simplification/code-sets"],
  oig:["HHS OIG — Fraud and abuse laws (False Claims, Anti-Kickback, Stark)","https://oig.hhs.gov/compliance/physician-education/fraud-abuse-laws/"],
  snf:["Medicare.gov — Skilled nursing facility care","https://www.medicare.gov/coverage/skilled-nursing-facility-snf-care"],
  homeHealth:["Medicare.gov — Home health services","https://www.medicare.gov/coverage/home-health-services"],
  hospice:["Medicare.gov — Hospice care","https://www.medicare.gov/coverage/hospice-care"],
  holidays:["OPM — Federal holidays","https://www.opm.gov/policy-data-oversight/pay-leave/federal-holidays/"],
  timeGov:["NIST — Official US time and time zones","https://www.time.gov/"],
  nato:["NATO — The phonetic alphabet (Alfa, Bravo, Charlie…)","https://www.nato.int/cps/en/natohq/declassified_136216.htm"],
  faaAlphabet:["FAA — Pilot/Controller Glossary (ICAO phonetic alphabet)","https://www.faa.gov/air_traffic/publications/atpubs/pcg_html/glossary-i.html"],
  aca:["HealthCare.gov — The Affordable Care Act","https://www.healthcare.gov/glossary/affordable-care-act/"],
  mec:["HealthCare.gov — Minimum essential coverage","https://www.healthcare.gov/glossary/minimum-essential-coverage/"],
  ptc:["HealthCare.gov — Premium tax credit","https://www.healthcare.gov/glossary/premium-tax-credit/"],
  fsaHsa:["IRS Publication 969 — HSAs, FSAs and other tax-favored health plans","https://www.irs.gov/publications/p969"],
  erisa:["DOL — ERISA and health plans","https://www.dol.gov/general/topic/health-plans/erisa"],
  medicareAppealsPub:["Medicare.gov — Medicare Appeals (publication 11525)","https://www.medicare.gov/publications/11525-medicare-appeals.pdf"],
  wcDol:["DOL — Workers' compensation","https://www.dol.gov/general/topic/workcomp"],
  mspLiability:["CMS — Coordination of Benefits & Recovery (liability, no-fault, workers' comp)","https://www.cms.gov/medicare/coordination-benefits-recovery/overview"],
  medicaidHome:["Medicaid.gov — Medicaid","https://www.medicaid.gov/medicaid/index.html"]
};
const BASICS_SOURCES={
  "us-culture":[S.holidays,S.timeGov],
  "us-fun-facts":[],
  "phonetic-alphabet":[S.nato,S.faaAlphabet],
  "hipaa":[S.hipaaPrivacy,S.hipaaTPO,S.hipaaMin,S.hipaaSecurity,S.hipaaBreach],
  "phi":[S.deid,S.hipaaPrivacy],
  "aca":[S.aca,S.mec,S.ptc,S.hcPreventive,S.hcGrace],
  "us-vs-india":[S.hcGlossary],
  "billing-vs-rcm":[S.hcGlossary],
  "why-insurance":[S.hcGlossary,S.mec],
  "three-ps":[S.npi,S.hcGlossary],
  "patient-terms":[S.em,S.abn],
  "providers-facilities":[S.snf,S.homeHealth,S.hospice,S.npi],
  "pos":[S.pos,S.posDb],
  "policy-people":[S.hcGlossary],
  "insurance-types":[S.hcGlossary,S.cobra,S.wcDol],
  "key-dates":[S.hcGlossary,S.hcGrace],
  "aob-waiting-cooling":[S.cms1500,S.medigapSwitch,S.hcGrace,S.cobra],
  "cost-sharing":[S.hcGlossary,S.hcOOP],
  "financial-responsibility":[S.hcGlossary,S.pfs],
  "par-nonpar":[S.nsa,S.nsaProvider,S.medicaidTPL],
  "contracts-networks":[S.pecos,S.npi],
  "ancillary-plans":[S.partD,S.hcGlossary],
  "managed-care":[S.hcGlossary],
  "cob":[S.cobOverview,S.msp,S.mspSize,S.howMedicareWorks,S.medicaidTPL],
  "rcm-overview":[S.ediBilling,S.hcGlossary],
  "scheduling":[S.hcGlossary],
  "registration":[S.cms1500,S.nucc],
  "eligibility":[S.edi,S.hcGrace],
  "encounter":[S.em],
  "coding-overview":[S.codeSets,S.icd,S.hcpcs,S.cpt,S.ncci],
  "icd10":[S.icd,S.icdCdc],
  "cpt-hcpcs":[S.cpt,S.hcpcs,S.em,S.ncci],
  "modifiers":[S.ncci,S.hcpcs,S.abn],
  "charge-entry":[S.cms1500,S.nucc],
  "claim-forms":[S.cms1500,S.nucc,S.nubc,S.edi],
  "clearinghouse":[S.ediBilling,S.edi],
  "adjudication":[S.ediBilling,S.hcGlossary],
  "payment-posting":[S.ediBilling],
  "ar-followup":[S.ediBilling],
  "denial-management":[S.appeals,S.redetermination],
  "credit-balance":[S.overpay],
  "patient-collections":[S.nsa,S.medicaidTPL],
  "federal-overview":[S.partsOfMedicare,S.medicaidHome,S.tricare,S.champva,S.chip,S.fehb,S.ihs,S.pace,S.oig],
  "medicare-msp":[S.whoPaysFirst,S.msp,S.mspSize,S.mspManual2,S.mspEsrd,S.mspDisability,S.howMedicareWorks,S.opmPaysFirst,S.mspLiability],
  "medicare":[S.partsOfMedicare,S.cmsCosts,S.cmsCostsMM,S.partD,S.mbi,S.mbiOverview,S.medigap,S.msp,S.abn],
  "medicaid":[S.medicaidHome,S.medicaidElig,S.medicaidTPL],
  "military-other-federal":[S.tricare,S.tricareElig,S.champva,S.chip,S.fehb,S.ihs,S.pace,S.paceMedicaid],
  "commercial-payers":[S.erisa,S.hcGlossary],
  "liability-wc":[S.mspLiability,S.wcDol,S.msp],
  "plan-money-terms":[S.hcGlossary,S.hcOOP,S.oop2026,S.mec,S.ptc],
  "care-settings-terms":[S.hcGlossary,S.pos,S.snf,S.homeHealth,S.hospice,S.hcPreventive],
  "drug-benefits":[S.hcGlossary,S.partD,S.hcpcs],
  "plan-types-depth":[S.hcGlossary,S.cobra,S.cobraFaq,S.erisa,S.fsaHsa],
  "cob-secondary-payment":[S.naicCob,S.cobOverview,S.cms1500,S.nucc,S.medicaidTPL,S.edi],
  "cob-government":[S.medicaidTPL,S.tricareOhi,S.champvaCare,S.ihs,S.opmPaysFirst,S.whoPaysFirst],
  "cob-seven-rules":[S.naicCob,S.cobOverview,S.whoPaysFirst,S.msp,S.medicaidTPL,S.tricareOhi,S.champvaCare,S.howMedicareWorks],
  "edi-electronic-claims":[S.edi,S.ediBilling,S.codeSets,S.cms1500,S.nubc],
  "appeals-grievances":[S.appeals,S.redetermination,S.medicareAppealsPub,S.hcGlossary],
  "janes-year":[S.hcGlossary,S.hcOOP],
  "acronyms":[S.hcGlossary,S.codeSets]
};
/* Figures that change on a schedule. Shown on the course page so someone re-checks them. */
const FIGURES_REVIEW=[
 {item:"Medicare Part A deductible and Part B deductible and premium",now:"$1,736 / $283 / $202.90 (2026)",changes:"Every January",source:S.cmsCosts},
 {item:"Medicare Part D out-of-pocket cap",now:"$2,100 (2026)",changes:"Every January",source:S.partD},
 {item:"Federal maximum out-of-pocket limit (ACA plans)",now:"$10,600 individual / $21,200 family (2026)",changes:"Every January",source:S.oop2026},
 {item:"ICD-10-CM code set and guidelines",now:"FY 2026 edition",changes:"Every 1 October",source:S.icd},
 {item:"CPT and HCPCS Level II code sets",now:"2026 editions",changes:"Every 1 January (HCPCS also quarterly)",source:S.hcpcs},
 {item:"TRICARE regional contractors",now:"East: Humana Military · West: TriWest",changes:"On contract change (last: 1 Jan 2025)",source:S.tricare},
 {item:"Medicare Advantage, Medigap and Marketplace enrolment dates",now:"AEP 15 Oct – 7 Dec; Marketplace OEP 1 Nov – 15 Jan",changes:"Confirm each autumn",source:S.partsOfMedicare}
];
/* Review reminder. The January review picks up every figure that changes with the
   new year: Medicare deductibles and premiums, the federal out-of-pocket maximum,
   the Part D cap, the new CPT and HCPCS editions. The other quarters catch mid-year
   changes: the 1 October ICD-10-CM release, HCPCS quarterly updates, TRICARE or MAC
   contractor changes. Update lastReviewed after each check; the app works out the
   next due date and flags it when it is overdue. */
const REVIEW_SCHEDULE={
  lastReviewed:"2026-10-07",                 // ISO date of the last full check (same as SOURCES_REVIEWED)
  dueOn:["01-15","04-15","07-15","10-15"],   // month-day of each quarterly review
  januaryItems:["Medicare Part A and Part B deductibles and the Part B premium","Part D out-of-pocket cap","Federal out-of-pocket maximum for ACA plans","CPT and HCPCS Level II editions"],
  otherQuarters:["ICD-10-CM edition (1 October)","HCPCS quarterly additions","TRICARE and MAC contractor changes","Payer IDs and portal names on the commercial payers topic"],
  reviewer:"Training team: send a correction through Feedback when a figure has moved."
};
